name: Docs

on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - run: dotnet tool update -g docfx

      # Clone icarus repositories
      - run: git clone https://github.com/altv-icarus/Commands.git docs/src
      - run: git clone https://github.com/altv-icarus/IoC.git docs/src
      - run: git clone https://github.com/altv-icarus/Chat.git docs/src

      - run: docfx docs/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2