name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - run: dotnet tool update -g docfx

      - run: ls -lah

      # Clone atlas repositories
      - run: git clone https://github.com/altv-atlas/Commands.git docs/src/AltV.Atlas.Commands
      - run: git clone https://github.com/altv-atlas/Chat.git docs/src/AltV.Atlas.Chat

      - run: git clone https://github.com/altv-atlas/IoC.git docs/src/AltV.Atlas.IoC
      - run: git clone https://github.com/altv-atlas/Client.Configuration.git docs/src/AltV.Atlas.Client.Configuration
      
      - run: git clone https://github.com/altv-atlas/Peds.git docs/src/AltV.Atlas.Peds
      - run: git clone https://github.com/altv-atlas/Peds.Client.git docs/src/AltV.Atlas.Peds.Client
      - run: git clone https://github.com/altv-atlas/Peds.Shared.git docs/src/AltV.Atlas.Peds.Shared
      
      - run: git clone https://github.com/altv-atlas/Vehicles.Server.git docs/src/AltV.Atlas.Vehicles.Server
      - run: git clone https://github.com/altv-atlas/Vehicles.Client.git docs/src/AltV.Atlas.Vehicles.Client
      - run: git clone https://github.com/altv-atlas/Vehicles.Shared.git docs/src/AltV.Atlas.Vehicles.Shared

      - run: docfx docs/docfx.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2